title: "Omor Ekushe - Win32 Bengali Keyboard Engine"
description: "A lightweight, high-performance, 100% native Win32 Bengali (Bangla) Keyboard Layout Manager & Engine for Windows."
baseurl: "/OmorEkushe"
url: "https://sabbir28.github.io"
github_username: sabbir28
github_repo: OmorEkushe
author: "Sabbir"
lang: "bn-BD"
keywords: "Bengali Keyboard, Win32, Bangla Keyboard, Bijoy, Unijoy, C++17, Windows Keyboard Layout Engine"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true

permalink: /:basename.html
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

